[Filters]
# Search only for these phrases in Name field (comma separated)
include_names = MSI, SMS, HP
# Ignore these phrases in Name field (comma separated)
exclude_names = xbox,

[Timeout]
# Force process kill if stop fails? (True/False)
taskkill_enabled = True
# How many seconds to wait before using taskkill?
stop_timeout = 10

[Groups]
RMI = 192.168.1.24,
DHS = 127.0.0.1,
ONLINE = 127.0.0.1,192.168.1.24

[Logging]
# Path to user action log file
log_file = action_history.log

[Settings]
# Path to Total Commander executable (e.g. C:\totalcmd\totalcmd64.exe)
# Leave empty to look in system PATH
totalcmd_path = c:\Program Files\totalcmd\TOTALCMD64.EXE
# Wait configuration for service state transitions
wait_attempts = 10
wait_interval = 0.5
